LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE IMDB_TITLE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID             INTEGER EXTERNAL,
  NAME           CHAR(200),
  RUNTIME_MIN    INTEGER EXTERNAL,
  START_YEAR     INTEGER EXTERNAL,
  END_YEAR       INTEGER EXTERNAL
)