LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE IMDB_ROLE_IN_TITLE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  TITLE_ID    INTEGER EXTERNAL,
  PERSON_ID   INTEGER EXTERNAL,
  PERSON_ROLE CHAR(50)
)